name: Java CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-2019
    timeout-minutes: 15
    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2.3.4

      - name: ☕ Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1.1.1
        with:
          version: '11'
          architecture: x64

      - name: 📦 Test with Maven
        run: mvn test -fae --no-transfer-progress
