name: Deploy
on:
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: windows-2019
    environment: Compile
    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2.3.4

      - name: ☕ Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1.1.1
        with:
          version: '11'
          architecture: x64

      - name: 📚 Install jpackage
        uses: AdoptOpenJDK/install-jdk@v1.1.1
        with:
          version: '15'
          architecture: x64

      - name: 📦 Build with Maven
        run: mvn -B package --file pom.xml

      - name: 📦 Compile to exe
        run: sh ./build.sh

      - name: 🚀 Deploy Installer to Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'rexedia-*.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rexedia
          path: rexedia

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: rexedia
          path: rexedia

      - name: 📦 Zip file
        uses: papeloto/action-zip@v1
        with:
          files: rexedia
          dest: rexedia.zip

      - name: 🚀 Deploy Binaries to Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'rexedia.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
