name: Deploy
on:
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2

      - name: ☕ Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: 📦 Build with Maven
        run: mvn -B package --file pom.xml

      - name: 📦 Compile to exe
        run: sh ./build.sh

      - name: 📦 Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rexedia
          path: rexedia

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: rexedia
          path: rexedia

      - name: 📦 Zip file
        uses: papeloto/action-zip@v1
        with:
          files: rexedia
          dest: rexedia.zip

      - name: 💾 Save to Releases
        uses: JasonEtco/upload-to-release@master
        with:
          args: rexedia.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}